"""Postga user_tg_id qo'shildi

Revision ID: 0dc6db8932d4
Revises: 2b6e27358030
Create Date: 2025-06-20 10:11:03.258650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc6db8932d4'
down_revision: Union[str, None] = '2b6e27358030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'districts', ['id'])
    op.add_column('posts', sa.Column('user_tg_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'regions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'regions', type_='unique')
    op.drop_column('posts', 'user_tg_id')
    op.drop_constraint(None, 'districts', type_='unique')
    # ### end Alembic commands ###
