"""region va district

Revision ID: 2b6e27358030
Revises: d47cc5afdbbf
Create Date: 2025-06-03 10:50:43.452294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b6e27358030'
down_revision: Union[str, None] = 'd47cc5afdbbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('posts', sa.Column('region_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('district_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'districts', ['district_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'regions', ['region_id'], ['id'])
    op.create_unique_constraint(None, 'sub_categories', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_categories', type_='unique')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'district_id')
    op.drop_column('posts', 'region_id')
    op.drop_table('districts')
    op.drop_table('regions')
    # ### end Alembic commands ###
