"""sub category

Revision ID: d47cc5afdbbf
Revises: 621ec651ba6a
Create Date: 2025-06-03 09:01:48.325590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd47cc5afdbbf'
down_revision: Union[str, None] = '621ec651ba6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'categories', ['id'])
    op.create_unique_constraint(None, 'post_photos', ['id'])
    op.add_column('posts', sa.Column('sub_category_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'posts', ['id'])
    op.create_foreign_key(None, 'posts', 'sub_categories', ['sub_category_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'sub_category_id')
    op.drop_constraint(None, 'post_photos', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_table('sub_categories')
    # ### end Alembic commands ###
